In [2]:
import warnings
import itertools
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [5]:
data = sm.datasets.co2.load_pandas()
y = data.data

print(y)

              co2
1958-03-29  316.1
1958-04-05  317.3
1958-04-12  317.6
1958-04-19  317.5
1958-04-26  316.4
1958-05-03  316.9
1958-05-10    NaN
1958-05-17  317.5
1958-05-24  317.9
1958-05-31    NaN
1958-06-07    NaN
1958-06-14    NaN
1958-06-21    NaN
1958-06-28    NaN
1958-07-05  315.8
1958-07-12  315.8
1958-07-19  315.4
1958-07-26  315.5
1958-08-02  315.6
1958-08-09  315.1
1958-08-16  315.0
1958-08-23    NaN
1958-08-30  314.1
1958-09-06  313.5
1958-09-13    NaN
1958-09-20    NaN
1958-09-27    NaN
1958-10-04    NaN
1958-10-11    NaN
1958-10-18    NaN
...           ...
2001-06-09  373.1
2001-06-16  372.8
2001-06-23  372.9
2001-06-30  372.7
2001-07-07  372.1
2001-07-14  371.3
2001-07-21  371.2
2001-07-28  370.6
2001-08-04  369.9
2001-08-11  369.5
2001-08-18  369.3
2001-08-25  369.0
2001-09-01  368.4
2001-09-08  368.2
2001-09-15  368.0
2001-09-22  367.4
2001-09-29  367.4
2001-10-06  367.8
2001-10-13  367.6
2001-10-20  368.1
2001-10-27  368.7
2001-11-03  368.7
2001-11-10  368.8
2001-11-17  369.7
2001-11-24  370.3
2001-12-01  370.3
2001-12-08  370.8
2001-12-15  371.2
2001-12-22  371.3
2001-12-29  371.5

[2284 rows x 1 columns]

In [4]:
# The 'MS' string groups the data in buckets by start of the month
y = y['co2'].resample('MS').mean()

# The term bfill means that we use the value before filling in missing values
y = y.fillna(y.bfill())

print(y)

1958-03-01    316.100000
1958-04-01    317.200000
1958-05-01    317.433333
1958-06-01    315.625000
1958-07-01    315.625000
1958-08-01    314.950000
1958-09-01    313.500000
1958-10-01    313.425000
1958-11-01    313.425000
1958-12-01    314.700000
1959-01-01    315.500000
1959-02-01    316.700000
1959-03-01    316.733333
1959-04-01    317.675000
1959-05-01    318.325000
1959-06-01    318.025000
1959-07-01    316.525000
1959-08-01    314.900000
1959-09-01    313.825000
1959-10-01    313.400000
1959-11-01    314.875000
1959-12-01    315.525000
1960-01-01    316.380000
1960-02-01    316.975000
1960-03-01    317.575000
1960-04-01    319.120000
1960-05-01    319.925000
1960-06-01    319.450000
1960-07-01    318.060000
1960-08-01    315.775000
                 ...
1999-07-01    369.000000
1999-08-01    366.700000
1999-09-01    364.675000
1999-10-01    365.140000
1999-11-01    366.650000
1999-12-01    367.900000
2000-01-01    369.020000
2000-02-01    369.375000
2000-03-01    370.400000
2000-04-01    371.540000
2000-05-01    371.650000
2000-06-01    371.625000
2000-07-01    369.940000
2000-08-01    367.950000
2000-09-01    366.540000
2000-10-01    366.725000
2000-11-01    368.125000
2000-12-01    369.440000
2001-01-01    370.175000
2001-02-01    371.325000
2001-03-01    372.060000
2001-04-01    372.775000
2001-05-01    373.800000
2001-06-01    373.060000
2001-07-01    371.300000
2001-08-01    369.425000
2001-09-01    367.880000
2001-10-01    368.050000
2001-11-01    369.375000
2001-12-01    371.020000
Freq: MS, Name: co2, Length: 526, dtype: float64

In [ ]:
y.plot(figsize=(15, 6))
plt.show()